### ISSUE TITLE
ssl 문제로 사이트 접근이 어렵습니다. 

### ISSUE THREAD

**Issue by jjuwoo** [parti-coop/data-micro-public-view#12]
공공의 창 페이지로 접근을 시도하면 인증서가 올바르지 않아 사이트 연결이 되지 않고 있습니다. 
인증서 확인부탁드립니다. 
public-view.org, public-view.kr

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/10860472/220164182-e2c17492-44d3-4e2a-9d70-0deba18a9e19.png">

**Comment by dalikim** [comment]
고쳐 두었습니다.

**Comment by jjuwoo** [comment]
감사합니다.
